//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCardDiags
{
    using System;
    using System.Collections.Generic;
    
    public partial class listObservPlans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public listObservPlans()
        {
            this.listObservPlanDetails = new HashSet<listObservPlanDetails>();
        }
    
        public int PlanCode { get; set; }
        public Nullable<int> ObservTypeCode { get; set; }
        public string PlanName { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listObservPlanDetails> listObservPlanDetails { get; set; }
    }
}
