//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCardDiags
{
    using System;
    using System.Collections.Generic;
    
    public partial class listObservPlanDetails
    {
        public int PlanCode { get; set; }
        public int Item { get; set; }
        public Nullable<int> OrganCode { get; set; }
        public Nullable<int> Parent { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
    
        public virtual listObservPlans listObservPlans { get; set; }
        public virtual listOrgans listOrgans { get; set; }
    }
}
