//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCardDiags
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbIcmEntities : DbContext
    {
        public dbIcmEntities()
            : base("name=dbIcmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<listObservPlanDetails> listObservPlanDetails { get; set; }
        public virtual DbSet<listObservPlans> listObservPlans { get; set; }
        public virtual DbSet<listOrgans> listOrgans { get; set; }
    }
}
