//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKMObserver
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstObservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hstObservations()
        {
            this.hstObservationDetails = new HashSet<hstObservationDetails>();
        }
    
        public System.Guid PatientID { get; set; }
        public int HistoryItem { get; set; }
        public Nullable<int> ObservTypeCode { get; set; }
        public string ObservReport { get; set; }
        public string ObservNotes { get; set; }
        public string TemplateName { get; set; }
        public string NotesTemplateName { get; set; }
        public Nullable<System.DateTime> ObservTime { get; set; }
        public string ObservDeviceType { get; set; }
        public string ObservDeviceID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hstObservationDetails> hstObservationDetails { get; set; }
    }
}
