//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKMObserver
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstObservationDetailData
    {
        public System.Guid PatientID { get; set; }
        public int HistoryItem { get; set; }
        public int Item { get; set; }
        public int ChunkNum { get; set; }
        public byte[] Data { get; set; }
        public string RecStatus { get; set; }
        public Nullable<System.Guid> CreatorID { get; set; }
        public System.DateTime WhenCreated { get; set; }
        public Nullable<System.Guid> EditorID { get; set; }
        public Nullable<System.DateTime> WhenEdited { get; set; }
        public string WorkstationName { get; set; }
    
        public virtual hstObservationDetails hstObservationDetails { get; set; }
    }
}
