//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKMObserver
{
    using System;
    using System.Collections.Generic;
    
    public partial class hstObservationDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hstObservationDetails()
        {
            this.hstObservationDetailData = new HashSet<hstObservationDetailData>();
        }
    
        public System.Guid PatientID { get; set; }
        public int HistoryItem { get; set; }
        public int Item { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> ObservDataTypeCode { get; set; }
        public string PointName { get; set; }
        public Nullable<int> ReportGroupCode { get; set; }
        public Nullable<int> OrganCode { get; set; }
        public Nullable<bool> Report { get; set; }
        public Nullable<int> Rating { get; set; }
        public byte[] Thumbnail { get; set; }
        public string DataType { get; set; }
        public string DataLocation { get; set; }
        public string Notes { get; set; }
        public string RecStatus { get; set; }
        public Nullable<System.Guid> CreatorID { get; set; }
        public System.DateTime WhenCreated { get; set; }
        public Nullable<System.Guid> EditorID { get; set; }
        public Nullable<System.DateTime> WhenEdited { get; set; }
        public string WorkstationName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hstObservationDetailData> hstObservationDetailData { get; set; }
        public virtual hstObservations hstObservations { get; set; }
    }
}
